- group:
    name: ssl-cert

- copy:
    src: forgeservicelab.fi.key
    dest: "{{ forge_ssl_key }}"
    owner: root
    group: ssl-cert
    mode: 0640
  sudo: true

- copy:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
    owner: root
    group: root
    mode: 0644
  with_together:
    - [forgeservicelab.fi.crt, forgeservicelab.fi.crt.chain, forgeservicelab.fi.crt.wholechain]
    - ["{{ forge_ssl_cert }}", "{{ forge_ssl_cert_chain }}", "{{ forge_ssl_cert_wholechain }}", "{{ dhparams_path }}"]
  sudo: true

- copy:
    content: "{{ dhparam }}"
    dest: "{{ dhparams_path }}"
    owner: root
    group: root
    mode: 0644
  sudo: true
